"use strict";

const projects = [
  {title:"Autonomous Ackermann Vehicle",category:"Robotics",code:"ROB-01",summary:"A ROS-based autonomous vehicle combining localization, path tracking and embedded actuation.",stack:["ROS","Gazebo","Raspberry Pi","IMU","Pure Pursuit"],detail:"Implemented pure-pursuit lateral control and proportional velocity control using IMU and encoder feedback. Iterated the steering mechanism to connect simulation with a working Ackermann platform."},
  {title:"Linear MPC for EV Anti-lock Braking",category:"Control",code:"CTL-02",summary:"Constrained predictive control for wheel-slip regulation during electric-vehicle braking.",stack:["MATLAB","Simulink","MPC","Vehicle Dynamics"],detail:"Bachelor thesis covering longitudinal vehicle and wheel dynamics, tyre-slip behaviour, controller constraints and braking performance under changing road conditions."},
  {title:"Multi-Manipulator Pick & Place",category:"Robotics",code:"ROB-03",summary:"Two coordinated manipulators, a conveyor and vision-based object tracking.",stack:["Robotics","ArUco","Computer Vision","Trajectory Planning"],detail:"Built a coordinated workcell with two arms and a conveyor. Camera tracking and ArUco markers provided object identification and localization."},
  {title:"Tensegrity Rolling Robot",category:"Robotics",code:"ROB-04",summary:"Cable-actuated locomotion through controlled deformation of a tensegrity structure.",stack:["Tensegrity","Mechanical Design","Control","Prototyping"],detail:"Explored how cable actuation and structural deformation generate rolling locomotion in a lightweight compliant robotic structure at ARAtronics."},
  {title:"Autonomous Center-Pivot Irrigation",category:"Embedded",code:"EMB-05",summary:"Distributed sensing and moisture-driven control for precision irrigation.",stack:["Microcontrollers","PWM","Sensors","Remote UI","Safety ML"],detail:"Integrated four microcontrollers, soil-moisture sensing, PWM actuation, remote monitoring and a safety model into an autonomous irrigation prototype."},
  {title:"Connect Four AI Agent",category:"AI",code:"AI-06",summary:"A game-playing agent designed around search, evaluation and adversarial decision-making.",stack:["Python","Algorithms","Game AI","Search"],detail:"Developed an AI opponent for Connect Four, translating game state into tactical decisions through adversarial search and board evaluation."}
];
const grid=document.querySelector("#project-grid"), dialog=document.querySelector("#case-dialog");
function render(filter="All"){grid.replaceChildren(...projects.filter(p=>filter==="All"||p.category===filter).map(p=>{const article=document.createElement("article");article.className="project-card";article.innerHTML=`<div class="project-visual" aria-hidden="true"><span>${p.code}</span><b>${p.category}</b></div><div class="card-meta"><span>${p.code}</span><span>${p.category}</span></div><h3>${p.title}</h3><p>${p.summary}</p><div class="tags">${p.stack.slice(0,3).map(t=>`<span>${t}</span>`).join("")}</div><button class="case-link">View case study <span>↗</span></button>`;article.querySelector("button").addEventListener("click",()=>openCase(p));return article;}));}
function openCase(p){document.querySelector("#dialog-code").textContent=`${p.code} / ${p.category}`;document.querySelector("#dialog-title").textContent=p.title;document.querySelector("#dialog-detail").textContent=p.detail;document.querySelector("#dialog-tags").replaceChildren(...p.stack.map(t=>{const s=document.createElement("span");s.textContent=t;return s;}));dialog.showModal();}
document.querySelectorAll("[data-filter]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-filter]").forEach(b=>b.classList.toggle("active",b===button));render(button.dataset.filter);}));
dialog.querySelector(".close").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close();});render();
